### ISSUE TITLE
Better fit in the surrounding layout

### ISSUE THREAD

**Issue by milstan** [blindnet-io/privacy-components-web#176]
## Description

Currently the main page of the PRCI is non-reponsive, the later pages are responsive byt they change dramatically in size when the user interacts with them.

### Intended outcome

- [ ] Have the PRCI component take total width of the parent container (and have content centered horizonatally and vertically in it)
- [ ] (ideally, and optionally) have the PRCI component inherit fonts, bacground color from parent webpage - or expose those as parameters (inherit option seems better as it supposes less work for the implementing developer)
- [ ] (optionally and non-urgently) expose parameters to define the existance and look of border and buttons

**Comment by jboileau99** [comment]
> * [ ]  (ideally, and optionally) have the PRCI component inherit fonts, bacground color from parent webpage - or expose those as parameters (inherit option seems better as it supposes less work for the implementing developer)

@milstan We can do both! Something like `background: var(--bldn-privacy-request-background-color, inherit)` allows them to set it via the css variable or it will take the background of the parent if not set
