### ISSUE TITLE
📑 [Epic]: Kickstart Monorepo and Data Consumer Interface Component (DCI)

### ISSUE THREAD

**Issue by jboileau99** [blindnet-io/privacy-components-web#22]
## Description

Setup monorepo for all devkit web components, with PRCI and DCI as the initial two

### Intended outcome

- Monorepo containing PRCI and DCI web components
- Github pages displaying storybook for all components
- Simple UI for DCI

## Sub-tasks

- [x] https://github.com/blindnet-io/privacy-components-web/issues/33
- [ ] https://github.com/blindnet-io/privacy-components-web/issues/34
- [ ] Develop basic initial UI for DCI based on sketches
- [ ] Setup storybook + github pages to display DCI

## Stakeholders

@jboileau99 - Development
@noelmace - Mentoring + Help setting up monorepo
@Clementinev - DCI Sketches
@milstan - Tracking and input

**Comment by noelmace** [comment]
Check out https://open-wc.org/guides/community/component-libraries/ for good examples.

I'd also recommend you to join and ask questions to the "lit & friends" community [on Slack](https://join.slack.com/t/lit-and-friends/shared_invite/zt-1d3d1rw6c-F86XIdmcgysp_ZzFb_Qe3g) or Github.
